using System.Collections.Generic;
using UnityEngine;

namespace Tanker
{
    /// 다국어 문자열 테이블 (ko/en). 유저 노출 문자열은 전부 Loc.T/F를 거친다 (규약).
    /// 배열 인덱스: 0=한국어, 1=영어. 언어는 PlayerPrefs("lang")로 저장.
    public static class Loc
    {
        public const int KO = 0, EN = 1;
        static int lang = -1;

        public static int Lang
        {
            get { if (lang < 0) lang = PlayerPrefs.GetInt("lang", KO); return lang; }
        }

        public static void SetLang(int value)
        {
            lang = value;
            PlayerPrefs.SetInt("lang", value);
            PlayerPrefs.Save();
        }

        public static string T(string key) =>
            table.TryGetValue(key, out var v) ? v[Lang] : key;

        public static string F(string key, params object[] args) => string.Format(T(key), args);

        static readonly Dictionary<string, string[]> table = new Dictionary<string, string[]>
        {
            // 유닛
            ["unit.tank"] = new[] { "나", "Me" },
            ["unit.dps"] = new[] { "딜러", "DPS" },
            ["unit.healer"] = new[] { "힐러", "Healer" },
            ["unit.goblinA"] = new[] { "고블린A", "Goblin A" },
            ["unit.goblinB"] = new[] { "고블린B", "Goblin B" },
            ["unit.goblin"] = new[] { "고블린", "Goblin" },
            ["unit.archer"] = new[] { "해골 궁수", "Skeleton Archer" },
            ["unit.brute"] = new[] { "브루트", "Brute" },
            ["unit.bruteX"] = new[] { "브루트X", "Brute X" },
            ["unit.bruteY"] = new[] { "브루트Y", "Brute Y" },
            ["unit.warlord"] = new[] { "워로드", "Warlord" },

            // 인카운터·노드
            ["enc.goblin"] = new[] { "고블린 매복", "Goblin Ambush" },
            ["enc.backline"] = new[] { "백라인 사냥", "Backline Hunt" },
            ["enc.twin"] = new[] { "쌍둥이 브루트", "Twin Brutes" },
            ["enc.warlord"] = new[] { "오거 워로드", "Ogre Warlord" },
            // 분기 맵 방 타입 (v0.6)
            ["nodeT.Battle"] = new[] { "전투", "Battle" },
            ["nodeT.Elite"] = new[] { "엘리트", "Elite" },
            ["nodeT.Event"] = new[] { "함정", "Trap" },
            ["nodeT.Rest"] = new[] { "휴식", "Rest" },
            ["nodeT.Shop"] = new[] { "상점", "Shop" },
            ["nodeT.Treasure"] = new[] { "보물", "Loot" },
            ["nodeT.Boss"] = new[] { "보스", "Boss" },
            ["map.pick"] = new[] { "다음 방을 골라라 — 연결된 길로만 갈 수 있다", "Pick your next room — follow the paths" },
            ["treasure.h1"] = new[] { "보물 상자", "Treasure" },
            ["treasure.desc"] = new[] { "{0}G를 손에 넣었다. 카드도 한 장 챙겨 가라.", "You found {0}G. Take a card as well." },

            // 타이틀
            ["title.name"] = new[] { "탱 커", "T A N K E R" },
            ["title.sub"] = new[] { "공격 스킬은 없다. 팀은 내가 지킨다.", "No attack skills. I protect the team." },
            ["title.start"] = new[] { "던전에 들어간다", "Enter the Dungeon" },
            ["title.ver"] = new[] { "v1.0 — 심연의 확장", "v1.0 — Abyss Expansion" },
            ["title.lang"] = new[] { "English", "한국어" },

            // 설정 오버레이
            ["set.open"] = new[] { "설정", "Menu" },
            ["set.title"] = new[] { "설 정", "S E T T I N G S" },
            ["set.bgm"] = new[] { "배경음", "Music" },
            ["set.sfx"] = new[] { "효과음", "Sound FX" },
            ["set.lang"] = new[] { "언어: 한국어 ▸ English", "Language: English ▸ 한국어" },
            ["set.toTitle"] = new[] { "타이틀 화면으로", "Back to Title" },
            ["set.confirmTitle"] = new[] { "정말요? 진행 중인 원정이 사라져요", "Sure? Your expedition will be lost" },
            ["set.close"] = new[] { "닫기", "Close" },
            ["set.speedNormal"] = new[] { "전투 속도: 보통 ▸ 빠름", "Battle speed: Normal ▸ Fast" },
            ["set.speedFast"] = new[] { "전투 속도: 빠름 ▸ 보통", "Battle speed: Fast ▸ Normal" },
            ["end.time"] = new[] { "플레이 시간: {0}분 {1}초", "Play time: {0}m {1}s" },
            ["status.time"] = new[] { "플레이 {0}분", "{0} min played" },

            // 엔딩 추가
            ["end.retry"] = new[] { "새 원정 시작", "New Expedition" },
            ["map.gold"] = new[] { "골드", "Gold" },

            // 맵
            ["map.h1"] = new[] { "던전 진행", "Dungeon Progress" },
            ["map.enter"] = new[] { "진입 ▶", "Enter ▶" },
            ["map.owned"] = new[] { "보유: {0}", "Owned: {0}" },
            ["map.done"] = new[] { "[완료]", "[Done]" },

            // 이벤트
            ["ev.h1"] = new[] { "가시 함정 복도", "Spike Trap Corridor" },
            ["ev.desc"] = new[] { "복도 바닥 가득 녹슨 가시가 솟아 있다.\n누군가는 대가를 치러야 지나간다.", "Rusty spikes cover the corridor floor.\nSomeone must pay the price to pass." },
            ["ev.a"] = new[] { "내가 앞장선다  (나 -{0})", "I go first  (Me -{0})" },
            ["ev.b"] = new[] { "무너진 우회로 통행료  (-{0}G)", "Toll for the collapsed detour  (-{0}G)" },
            ["ev.c"] = new[] { "날렵한 딜러를 보낸다  (딜러 -{0}, 다음 전투 위축 시작)", "Send the nimble DPS  (DPS -{0}, next battle starts Shaken)" },
            ["ev.hint"] = new[] { "결과는 표기된 그대로다 — 숨은 주사위는 없다.", "What you see is what you get — no hidden dice." },

            // 갈림길·휴식·상점
            ["ch.h1"] = new[] { "갈림길", "Fork in the Path" },
            ["ch.desc"] = new[] { "왼쪽에선 모닥불 냄새가, 오른쪽에선 동전 소리가 난다.\n하나만 고를 수 있다.", "Campfire smoke to the left, clinking coins to the right.\nYou may pick only one." },
            ["ch.rest"] = new[] { "모닥불에서 쉰다  (전원 {0}% 회복)", "Rest at the campfire  (all heal {0}%)" },
            ["ch.shop"] = new[] { "상인에게 간다", "Visit the merchant" },
            ["rest.h1"] = new[] { "모닥불", "Campfire" },
            ["rest.desc"] = new[] { "잠시나마 등을 벽에 기댄다.\n\n나 +{0}   딜러 +{1}   힐러 +{2}", "For a moment, we rest our backs against the wall.\n\nMe +{0}   DPS +{1}   Healer +{2}" },
            ["rest.go"] = new[] { "계속 ▶", "Continue ▶" },
            ["shop.h1"] = new[] { "떠돌이 상인", "Wandering Merchant" },
            ["shop.soldout"] = new[] { "{0} — 품절", "{0} — Sold out" },
            ["shop.item"] = new[] { "{0}  ({1}G)\n{2}", "{0}  ({1}G)\n{2}" },
            ["shop.leave"] = new[] { "상점을 나선다 ▶", "Leave the shop ▶" },
            ["item.guard"] = new[] { "도발 함성", "Taunting Roar" },
            ["item.guard.desc"] = new[] { "도발된 적에게 받는 피해 -{0}", "-{0} damage taken from taunted enemies" },
            ["item.cover"] = new[] { "철벽 엄호", "Iron Cover" },
            ["item.cover.desc"] = new[] { "엄호로 대신 맞는 피해 -{0}", "-{0} damage taken when covering" },
            ["item.brace"] = new[] { "단단한 각오", "Hard Resolve" },
            ["item.brace.desc"] = new[] { "버티기 회복 +{0}", "Brace heal +{0}" },
            ["item.potion"] = new[] { "응급 물약", "Emergency Potion" },
            ["item.potion.desc"] = new[] { "즉시 탱커 {0} 회복", "Instantly heal the tank for {0}" },

            // 엔딩
            ["end.win.h1"] = new[] { "던전 정복", "Dungeon Conquered" },
            ["end.lose.h1"] = new[] { "원정 실패", "Expedition Failed" },
            ["end.win.desc"] = new[] { "아무도 죽지 않았다.\n그것이 탱커의 승리다.", "No one died.\nThat is a tanker's victory." },
            ["end.lose.desc"] = new[] { "지키지 못한 원정은 여기서 끝났다.", "The expedition I failed to protect ends here." },
            ["end.stats"] = new[] { "도달: {0}/{1} 층\n전투 승리: {2}\n대신 맞은 피해: {3}\n경감한 피해: {4}\n남은 골드: {5}G", "Reached: floor {0}/{1}\nBattles won: {2}\nDamage intercepted: {3}\nDamage reduced: {4}\nGold left: {5}G" },
            ["end.title"] = new[] { "타이틀로", "To Title" },

            // 전투 UI
            ["bt.header"] = new[] { "{0}턴  |  {1}", "Turn {0}  |  {1}" },
            ["bt.score"] = new[] { "보호 점수  대신 맞음 {0} · 경감 {1}", "Protection  intercepted {0} · reduced {1}" },
            ["skill.taunt"] = new[] { "도발", "Taunt" },
            ["skill.taunt.cd"] = new[] { "도발 (쿨 {0})", "Taunt (CD {0})" },
            ["skill.cover"] = new[] { "엄호", "Cover" },
            ["skill.brace"] = new[] { "버티기", "Brace" },
            ["skill.go"] = new[] { "진행 ▶", "Go ▶" },
            ["hint.taunt"] = new[] { "적 1명을 {0}턴간\n나에게 고정", "Lock one enemy\non me for {0} turns" },
            ["hint.cover"] = new[] { "아군 1명 대신\n내가 맞기", "Take the hits\nfor one ally" },
            ["hint.brace"] = new[] { "받는 피해 절반\n받은 만큼 회복(최대 {0})", "Halve damage taken\nheal what you took (max {0})" },
            ["hint.go"] = new[] { "진행 전엔 언제든\n예약 취소 가능", "Plans can be cancelled\nany time before Go" },
            ["st.dead"] = new[] { "사망", "Dead" },
            ["st.enraged"] = new[] { "격노", "Enraged" },
            ["st.enragedTaunt"] = new[] { "격노·도발됨 {0}", "Enraged·Taunted {0}" },
            ["st.taunted"] = new[] { "도발됨 {0}", "Taunted {0}" },
            ["st.planTaunt"] = new[] { "도발 예약", "Taunt planned" },
            ["st.planCover"] = new[] { "엄호 예약", "Cover planned" },
            ["st.planBrace"] = new[] { "버티기 예약", "Brace planned" },
            ["st.bracing"] = new[] { "버티는 중", "Bracing" },
            ["st.shaken"] = new[] { "위축", "Shaken" },
            ["st.covered"] = new[] { "엄호받는 중", "Covered" },
            ["st.incoming"] = new[] { "예상 -{0}", "Incoming -{0}" },
            ["intent.charge"] = new[] { "힘 모으는 중...", "Gathering power..." },
            ["intent.single"] = new[] { "▶ {0}에게 {1}", "▶ {1} to {0}" },
            ["intent.aoe"] = new[] { "▶ 휩쓸기: {0}", "▶ Sweep: {0}" },
            ["result.winT"] = new[] { "승 리", "V I C T O R Y" },
            ["result.winSub"] = new[] { "{0} 격파 — 아무도 잃지 않았다", "{0} cleared — no one was lost" },
            ["result.loseT"] = new[] { "패 배", "D E F E A T" },
            ["result.loseSub"] = new[] { "팀을 지키지 못했다...", "I couldn't protect them..." },
            ["result.stats"] = new[] { "대신 맞은 피해 {0} · 경감한 피해 {1}", "Intercepted {0} · Reduced {1}" },
            ["result.loot"] = new[] { "전리품 +{0}G", "Loot +{0}G" },
            ["result.continue"] = new[] { "계속 ▶", "Continue ▶" },
            ["result.view"] = new[] { "결과 보기", "See the outcome" },

            // 전투 로그·팝업
            ["log.t1"] = new[] { "1턴: 적의 공격 예고를 보고 팀을 지켜라", "Turn 1: read the telegraphs and protect the team" },
            ["log.turn"] = new[] { "{0}턴: 예고를 읽고 결정하라", "Turn {0}: read and decide" },
            ["log.trapShaken"] = new[] { "함정의 여파로 딜러가 위축된 채 전투 시작...", "The trap's toll lingers — DPS starts the battle Shaken..." },
            ["log.enrageBrute"] = new[] { "{0}이(가) 격노했다 — 이제 매 턴 공격한다!", "{0} is enraged — it attacks every turn now!" },
            ["log.enrageBoss"] = new[] { "{0}이(가) 격노했다 — 숨 돌릴 틈이 사라진다!", "{0} is enraged — no more breathing room!" },
            ["log.selCancel"] = new[] { "스킬 선택 취소", "Selection cancelled" },
            ["log.planCancel"] = new[] { "예약 취소 — 다른 스킬을 고르거나 그대로 진행", "Plan cancelled — pick another skill or just Go" },
            ["log.planBrace"] = new[] { "버티기 예약: 받는 피해 절반, 받은 만큼 회복(최대 {0}) (진행 시 확정)", "Brace planned: halve damage, heal what you take (max {0}) (commits on Go)" },
            ["log.pickTaunt"] = new[] { "도발할 적을 선택", "Choose an enemy to taunt" },
            ["log.pickCover"] = new[] { "엄호할 아군을 선택", "Choose an ally to cover" },
            ["log.planTaunt"] = new[] { "{0} 도발 예약 — {1}턴간 나만 공격한다 (진행 시 확정)", "Taunt planned on {0} — attacks only me for {1} turns (commits on Go)" },
            ["log.planCover"] = new[] { "{0} 엄호 예약 — 그를 노리는 공격은 내가 맞는다 (진행 시 확정)", "Cover planned on {0} — I take the hits aimed at them (commits on Go)" },
            ["log.dpsHit"] = new[] { "딜러가 {0}에게 {1} 피해", "DPS hits {0} for {1}" },
            ["log.charging"] = new[] { "{0}이(가) 힘을 모은다...", "{0} is gathering power..." },
            ["log.redirect"] = new[] { "{0}을(를) 노린 공격을 내가 받아냈다 ({1})", "I intercepted the attack aimed at {0} ({1})" },
            ["log.aoeRedirect"] = new[] { "{0} 몫의 휩쓸기를 내가 받아냈다 ({1})", "I intercepted {0}'s share of the sweep ({1})" },
            ["log.aoeHit"] = new[] { "{0}의 휩쓸기가 {1}에게 {2} 피해", "{0}'s sweep hits {1} for {2}" },
            ["log.hit"] = new[] { "{0}이(가) {1}에게 {2} 피해", "{0} hits {1} for {2}" },
            ["log.heal"] = new[] { "힐러가 {0}을(를) {1} 회복", "Healer restores {0} for {1}" },
            ["log.braceHeal"] = new[] { "버티며 흘린 피를 추스른다 (+{0})", "Braced through it and recovered (+{0})" },
            ["log.win"] = new[] { "승리! 대신 맞음 {0} · 경감 {1}", "Victory! Intercepted {0} · Reduced {1}" },
            ["log.lose"] = new[] { "{0} 사망... 탱커의 실패다", "{0} has fallen... the tanker failed" },
            ["pop.enrage"] = new[] { "격노!!", "ENRAGED!!" },
            ["pop.taunt"] = new[] { "도발!", "Taunt!" },
            ["pop.cover"] = new[] { "엄호", "Cover" },
            ["pop.brace"] = new[] { "+{0} 버티기", "+{0} Brace" },
            ["pop.taken"] = new[] { "-{0} 대신 맞음!", "-{0} intercepted!" },
            ["pop.shaken"] = new[] { "위축!", "Shaken!" },

            // ---- v0.4: 클래스 ----
            ["class.warrior"] = new[] { "전사", "Warrior" },
            ["class.rogue"] = new[] { "도적", "Rogue" },
            ["class.mage"] = new[] { "마법사", "Mage" },
            ["class.ranger"] = new[] { "궁수", "Ranger" },
            ["class.assassin"] = new[] { "암살자", "Assassin" },
            ["class.beastkin"] = new[] { "수인", "Beastkin" },
            ["class.cleric"] = new[] { "클레릭", "Cleric" },
            ["class.paladin"] = new[] { "성기사", "Paladin" },
            ["class.berserker"] = new[] { "광전사", "Berserker" },
            ["class.bard"] = new[] { "음유시인", "Bard" },
            ["trait.TankHealOnHit"] = new[] { "특성: 공격할 때마다 탱커 {0} 회복", "Trait: heals the tank {0} on every attack" },
            ["trait.Frenzy"] = new[] { "특성: HP 절반 이하면 공격력 2배", "Trait: double damage below half HP" },
            ["trait.Cleanse"] = new[] { "특성: 공격 후 위축된 아군 1명 해제", "Trait: clears Shaken from an ally after attacking" },
            ["trait.FullHpDouble"] = new[] { "특성: HP가 가득이면 공격력 2배", "Trait: double damage at full HP" },
            ["trait.KillChain"] = new[] { "특성: 적을 처치하면 즉시 한 번 더 공격", "Trait: strikes again on a kill" },
            ["trait.Momentum"] = new[] { "특성: 같은 적 연속 공격마다 공격력 +1 누적", "Trait: +1 damage per consecutive hit on the same foe" },
            ["trait.GoldOnKill"] = new[] { "특성: 적 처치 시 골드 획득", "Trait: earns gold on kills" },
            ["trait.ArcaneNova"] = new[] { "특성: 3턴마다 모든 적에게 광역 마법", "Trait: hits all foes every 3rd turn" },
            ["trait.Sniper"] = new[] { "특성: 항상 가장 위협적인 적을 저격", "Trait: always snipes the deadliest foe" },
            ["trait.FirstStrike"] = new[] { "특성: 전투 첫 턴 공격력 2배", "Trait: double damage on turn one" },
            ["trait.Devour"] = new[] { "특성: 적 처치 시 자신을 회복", "Trait: heals itself on kills" },
            ["class.warden"] = new[] { "문지기", "Warden" },
            ["class.shadow"] = new[] { "그림자", "Shadow" },

            // ---- v0.4: 신규 적 ----
            ["unit.slime"] = new[] { "슬라임", "Slime" },
            ["unit.orc"] = new[] { "오크 전사", "Orc Warrior" },
            ["unit.shaman"] = new[] { "다크 샤먼", "Dark Shaman" },
            ["unit.spider"] = new[] { "독거미", "Venom Spider" },
            ["unit.golem"] = new[] { "가시 골렘", "Thorn Golem" },
            ["unit.bat"] = new[] { "흡혈 박쥐", "Vampire Bat" },
            ["unit.necro"] = new[] { "네크로맨서", "Necromancer" },
            ["unit.chief"] = new[] { "고블린 대장", "Goblin Chief" },
            ["unit.bomber"] = new[] { "폭탄꾼", "Bomber" },
            ["unit.thief"] = new[] { "도굴꾼", "Grave Robber" },
            ["unit.skeleton"] = new[] { "해골 방패병", "Skeleton Guard" },
            ["unit.wolf"] = new[] { "던전 늑대", "Dungeon Wolf" },
            ["unit.mimic"] = new[] { "미믹", "Mimic" },
            ["unit.armor"] = new[] { "저주받은 갑옷", "Cursed Armor" },
            ["unit.lich"] = new[] { "리치 왕", "Lich King" },
            ["enc.lich"] = new[] { "심연의 리치 왕", "Lich King of the Depths" },
            ["enc.random"] = new[] { "적 무리", "Enemy Band" }, // 폴백 — 실제 제목은 적 구성에서 생성
            ["enc.pack"] = new[] { "{0} 무리", "{0} Pack" },
            ["enc.ambush"] = new[] { "{0}의 습격", "{0} Ambush" },
            ["enc.eliteAmbush"] = new[] { "정예 — {0}의 습격", "Elite Ambush — {0}" },
            ["enc.elite"] = new[] { "정예 조우전", "Elite Encounter" },
            ["node.battleRandom"] = new[] { "전투 — 무작위 조우", "Battle — Random Encounter" },

            // ---- v0.4: 카드 ----
            ["card.Taunt"] = new[] { "도발", "Taunt" },
            ["card.Taunt.desc"] = new[] { "적 1명이 {0}턴간 나만 공격", "One enemy attacks only me for {0} turns" },
            ["card.Cover"] = new[] { "엄호", "Cover" },
            ["card.Cover.desc"] = new[] { "아군 1명의 첫 공격을 대신 맞음", "Intercept the first attack on an ally" },
            ["card.Brace"] = new[] { "버티기", "Brace" },
            ["card.Brace.desc"] = new[] { "피해 절반, 받은 만큼 회복(최대 {0})", "Halve damage, heal what you take (max {0})" },
            ["card.Shield"] = new[] { "철벽 방패", "Iron Bulwark" },
            ["card.Shield.desc"] = new[] { "아군 1명의 첫 피해 무효", "Block the first damage on an ally" },
            ["card.Shove"] = new[] { "밀쳐내기", "Shove" },
            ["card.Shove.desc"] = new[] { "적 1명 이번 턴 행동 취소 (보스 면역)", "Cancel one enemy's action (boss immune)" },
            ["card.Devotion"] = new[] { "헌신", "Devotion" },
            ["card.Devotion.desc"] = new[] { "내 HP {0} → 아군 회복 {0}", "Give {0} of my HP to heal an ally" },
            ["card.Rally"] = new[] { "사기 고취", "Rally" },
            ["card.Rally.desc"] = new[] { "아군 1명 위축 해제", "Remove Shaken from an ally" },
            ["card.Phalanx"] = new[] { "결사 방어", "Last Stand" },
            ["card.Phalanx.desc"] = new[] { "이번 턴 아군 전원 피해 -{0}", "All allies take -{0} damage this turn" },
            ["card.Oath"] = new[] { "반석의 맹세", "Oath of Stone" },
            ["card.Oath.desc"] = new[] { "{1}턴간 내가 받는 피해 -{0}", "I take -{0} damage for {1} turns" },
            // 카드 버튼용 짧은 설명 (카드 폭 안에 들어가야 함)
            ["card.IronWill"] = new[] { "철의 의지", "Iron Will" },
            ["card.IronWill.desc"] = new[] { "이번 턴 내가 받는 한 방 피해 상한 {0}", "This turn each hit on me deals at most {0}" },
            ["card.GuardianMark"] = new[] { "수호 낙인", "Guardian Mark" },
            ["card.GuardianMark.desc"] = new[] { "이번 턴 그 아군 피해의 절반을 내가 분담", "I absorb half of that ally's damage this turn" },
            ["card.Respite"] = new[] { "숨 고르기", "Respite" },
            ["card.Respite.desc"] = new[] { "즉시 내 HP {0} 회복", "Instantly restore {0} of my HP" },
            ["card.ThornStance"] = new[] { "가시 태세", "Thorn Stance" },
            ["card.ThornStance.desc"] = new[] { "이번 턴 나를 때린 적에게 {0} 반사", "This turn, attackers who hit me take {0}" },
            ["card.ThornStance.s"] = new[] { "피격 반사", "Retaliate" },
            ["card.FirstAid"] = new[] { "응급 처치", "First Aid" },
            ["card.FirstAid.desc"] = new[] { "아군 1명 즉시 {0} 회복", "Instantly heal an ally for {0}" },
            ["card.FirstAid.s"] = new[] { "아군 회복", "Heal ally" },
            ["card.Regroup"] = new[] { "재정비", "Regroup" },
            ["card.Regroup.desc"] = new[] { "이번 턴 남은 손패를 버리지 않는다", "Keep your unplayed hand this turn" },
            ["card.Regroup.descPlus"] = new[] { "손패 유지 + 다음 턴 1장 더 드로우", "Keep hand + draw 1 extra next turn" },
            ["card.Regroup.s"] = new[] { "손패 유지", "Keep hand" },
            ["card.WarCry"] = new[] { "도발 함성", "War Cry" },
            ["card.WarCry.desc"] = new[] { "적 전원이 1턴간 나만 공격 (폭탄은 못 막음)", "All enemies attack only me for 1 turn (can't stop bombs)" },
            ["card.WarCry.descPlus"] = new[] { "전원 도발 + 내 HP {0} 회복", "Taunt all + heal me {0}" },
            ["card.WarCry.s"] = new[] { "전원 도발", "Taunt all" },
            ["card.Cover.descPlus"] = new[] { "대신 맞고 그 피해 -{0}", "Intercept and take -{0} damage" },
            ["card.Shield.descPlus"] = new[] { "첫 {0}회 피해 무효", "Block the first {0} hits" },
            ["card.Shove.descPlus"] = new[] { "행동 취소 + 위축", "Cancel action + Shaken" },
            ["card.Rally.descPlus"] = new[] { "위축 해제 + {0} 회복", "Clear Shaken + heal {0}" },
            ["card.GuardianMark.descPlus"] = new[] { "피해 분담, 분담분 -{0}", "Share damage, my share -{0}" },

            ["card.Taunt.s"] = new[] { "적 고정 2턴", "Lock enemy 2t" },
            ["card.Cover.s"] = new[] { "대신 맞기", "Intercept" },
            ["card.Brace.s"] = new[] { "절반+회복", "Halve+heal" },
            ["card.Shield.s"] = new[] { "첫 피해 무효", "Block first hit" },
            ["card.Shove.s"] = new[] { "행동 취소", "Cancel action" },
            ["card.Devotion.s"] = new[] { "HP 나눔", "Give HP" },
            ["card.Rally.s"] = new[] { "위축 해제", "Clear Shaken" },
            ["card.Phalanx.s"] = new[] { "전원 -2", "All -2" },
            ["card.Oath.s"] = new[] { "2턴 -2", "2t -2" },
            ["card.IronWill.s"] = new[] { "한 방 상한", "Hit cap" },
            ["card.GuardianMark.s"] = new[] { "피해 분담", "Share damage" },
            ["card.Respite.s"] = new[] { "즉시 회복", "Self heal" },

            // v0.5 신규 매커니즘 팝업·로그
            ["pop.ironwill"] = new[] { "철의 의지!", "Iron Will!" },
            ["pop.mark"] = new[] { "수호 낙인!", "Marked!" },
            ["pop.thorns"] = new[] { "반사 -{0}", "Thorns -{0}" },
            ["log.necroHeal"] = new[] { "{0}이(가) {1}을(를) 치유한다", "{0} mends {1}" },
            ["log.necroIdle"] = new[] { "{0}이(가) 주문을 고른다", "{0} ponders a spell" },
            ["intent.heal"] = new[] { "회복 ▶ {0}", "Heal ▶ {0}" },
            ["intent.aoeMore"] = new[] { " 외 {0}", " +{0} more" },

            // v0.6 — 전투 하단 UI 개편
            ["bt.draw"] = new[] { "뽑을 {0}", "Draw {0}" },
            ["bt.discard"] = new[] { "버림 {0}", "Discard {0}" },
            ["bt.drawL"] = new[] { "뽑을 더미", "Draw pile" },
            ["bt.discardL"] = new[] { "버림 더미", "Discard" },
            ["bt.deckView"] = new[] { "내 덱 {0}", "Deck {0}" },
            ["bt.plan"] = new[] { "예약: {0} — 진행하면 발동", "Planned: {0} — resolves on Go" },
            ["bt.planTarget"] = new[] { "예약: {0} ▶ {1} — 진행하면 발동", "Planned: {0} ▶ {1} — resolves on Go" },
            ["bt.pickTarget"] = new[] { "{0} — 빛나는 대상을 탭하라", "{0} — tap a glowing target" },
            ["deck.title"] = new[] { "내 덱 — {0}장", "My Deck — {0} cards" },
            ["deck.sub"] = new[] { "손 {0} · 뽑을 더미 {1} · 버림 더미 {2}", "Hand {0} · Draw {1} · Discard {2}" },
            ["badge.enemy"] = new[] { "◆ 적 대상", "◆ Enemy" },
            ["badge.ally"] = new[] { "◆ 아군 대상", "◆ Ally" },
            ["badge.self"] = new[] { "◆ 즉시/자신", "◆ Instant/Self" },
            ["st.frenzy"] = new[] { "격노 ×2", "Frenzy ×2" },
            ["st.thorns"] = new[] { "가시 반사 {0}", "Thorns {0}" },
            ["st.lifesteal"] = new[] { "흡혈", "Lifesteal" },
            ["st.enemyHealer"] = new[] { "치유사", "Mender" },
            ["st.fullhp"] = new[] { "만전 ×2", "Prime ×2" },
            ["st.momentum"] = new[] { "기세 +{0}", "Momentum +{0}" },
            ["st.aura"] = new[] { "지휘 — 다른 적 공격 +1", "Command — allies +1" },
            ["st.pack"] = new[] { "무리 사냥", "Pack Hunter" },
            ["st.cap"] = new[] { "받는 피해 상한 {0}", "Damage capped {0}" },
            ["st.bounty"] = new[] { "전리품 {0}G", "Bounty {0}G" },

            // v0.8 — 2막·심층·상태
            ["log.enrageLich"] = new[] { "{0}이(가) 격노한다 — 폭풍이 잦아지지 않는다!", "{0} is enraged — the storm never rests!" },
            ["descend.h1"] = new[] { "워로드 격파", "Warlord Slain" },
            ["descend.desc"] = new[] { "던전 아래에서 더 깊은 어둠이 느껴진다.\n여기서 돌아가면 승리다. 하지만 심연의 주인은 따로 있다...", "A deeper darkness stirs below.\nTurn back now and claim victory — or face the true master of the abyss..." },
            ["descend.go"] = new[] { "심층으로 내려간다 (2막 — 훨씬 강한 적)", "Descend (Act 2 — far stronger foes)" },
            ["descend.return"] = new[] { "전리품을 챙겨 귀환한다 (승리)", "Return with the spoils (Victory)" },
            ["end.true.h1"] = new[] { "심연 정복", "ABYSS CONQUERED" },
            ["end.true.desc"] = new[] { "리치 왕마저 무릎 꿇었다. 완전한 승리다.", "Even the Lich King has fallen. Total victory." },
            ["end.act"] = new[] { "도달한 막: {0}막", "Act reached: {0}" },
            ["status.h1"] = new[] { "내 상태", "My Status" },
            ["status.meta"] = new[] { "{0}막 · {1}/{2}층 · {3}G", "Act {0} · Floor {1}/{2} · {3}G" },
            ["status.relics"] = new[] { "보유 유물 ({0})", "Relics ({0})" },
            ["status.noRelic"] = new[] { "아직 없다 — 엘리트·보물·상점에서 얻는다", "None yet — from elites, treasure and shops" },
            ["status.tap"] = new[] { "탭 = 상태", "tap = status" },

            // v0.8 — 도감
            ["codex.h1"] = new[] { "도감", "Codex" },
            ["codex.allies"] = new[] { "아군", "Allies" },
            ["codex.enemies"] = new[] { "몬스터", "Monsters" },
            ["codex.relics"] = new[] { "유물", "Relics" },
            ["codex.atkStat"] = new[] { "HP {0} · 공격 {1}", "HP {0} · ATK {1}" },
            ["codex.healStat"] = new[] { "HP {0} · 회복 {1}", "HP {0} · Heal {1}" },
            ["codex.healerTrait"] = new[] { "특성: 매 턴 가장 위험한 아군을 치유 (탱커 제외)", "Trait: heals the most endangered ally each turn (never the tank)" },
            ["cdx.goblin"] = new[] { "잡졸 — 힐러·최강 딜러·최저 HP를 노리는 변형이 있다", "Grunt — variants hunt your healer, top damage dealer or lowest HP" },
            ["cdx.archer"] = new[] { "힐러를 저격한다", "Snipes your healer" },
            ["cdx.slime"] = new[] { "약하지만 수가 많다", "Weak but plentiful" },
            ["cdx.orc"] = new[] { "최강 공격수만 노린다", "Fixates on your strongest attacker" },
            ["cdx.shaman"] = new[] { "공격 대신 저주로 위축시킨다 — 도발하면 낭비", "Curses instead of attacking — taunt to waste it" },
            ["cdx.spider"] = new[] { "같은 대상 연타 2회 — 엄호는 첫 타만 막는다", "Strikes twice — Cover blocks only the first" },
            ["cdx.brute"] = new[] { "차징 후 강타, 빈사 시 격노", "Charges then smashes; enrages when low" },
            ["cdx.golem"] = new[] { "때리면 1 반사 — 집중 공격이 아프다", "Reflects 1 per hit — focus fire hurts" },
            ["cdx.bat"] = new[] { "준 피해만큼 회복한다", "Heals for the damage it deals" },
            ["cdx.necro"] = new[] { "가장 다친 적을 치유한다 — 우선 처치", "Mends its wounded allies — kill it first" },
            ["cdx.chief"] = new[] { "살아있는 동안 다른 적 공격 +1", "Other enemies deal +1 while it lives" },
            ["cdx.bomber"] = new[] { "3턴 뒤 전원 폭발 — 그 전에 잡아라", "Explodes on everyone in 3 turns — kill it in time" },
            ["cdx.thief"] = new[] { "골드를 훔친다 — 처치하면 이자 붙여 회수", "Steals gold — kill it to reclaim with interest" },
            ["cdx.skeleton"] = new[] { "매 턴 방패로 첫 타를 막는다", "Blocks the first hit every turn" },
            ["cdx.wolf"] = new[] { "다른 늑대 수만큼 공격이 강해진다", "Hits harder for each other wolf alive" },
            ["cdx.mimic"] = new[] { "처치하면 골드를 쏟아낸다", "Bursts with gold when slain" },
            ["cdx.armor"] = new[] { "받는 한 방 피해 상한 3 — 소모전을 강요한다", "Caps incoming hits at 3 — a war of attrition" },
            ["cdx.boss"] = new[] { "1막 보스 — 차징·광역·강타 3턴 주기, 빈사 시 격노", "Act 1 boss — charge/AoE/smash cycle, enrages when low" },
            ["cdx.lich"] = new[] { "심연의 주인 — 사령 폭풍은 탱커까지 덮친다", "Master of the abyss — its storm hits even the tank" },

            // v0.7 — 신규 매커니즘 로그·팝업·인텐트
            ["pop.thornstance"] = new[] { "가시 태세!", "Thorn Stance!" },
            ["pop.regroup"] = new[] { "재정비!", "Regroup!" },
            ["pop.warcry"] = new[] { "도발 함성!", "War Cry!" },
            ["pop.chain"] = new[] { "연격!", "Chain!" },
            ["pop.boom"] = new[] { "쾅!", "BOOM!" },
            ["log.nova"] = new[] { "{0}의 비전 폭발 — 전원 {1}", "{0} unleashes a nova — {1} to all" },
            ["log.bomb"] = new[] { "{0}이(가) 폭발한다!", "{0} explodes!" },
            ["log.fuse"] = new[] { "{0}의 도화선 — {1}턴 남음", "{0}'s fuse — {1} turns left" },
            ["log.steal"] = new[] { "{0}이(가) {1}G를 훔쳤다 — 처치하면 되찾는다", "{0} stole {1}G — kill it to reclaim" },
            ["log.stealFail"] = new[] { "{0}이(가) 빈 주머니를 뒤진다", "{0} finds empty pockets" },
            ["intent.boom"] = new[] { "💥 이번 턴 폭발 — 전원 피격!", "Explodes THIS turn — hits everyone!" },
            ["intent.fuse"] = new[] { "폭발까지 {0}턴", "Explodes in {0}" },
            ["intent.steal"] = new[] { "골드를 노린다", "Eyeing your gold" },

            // v0.7 — 유물
            ["relic.h1"] = new[] { "유물 발견", "Relic Found" },
            ["relic.hint"] = new[] { "유물은 원정 내내 효과가 지속된다", "Relics last for the whole expedition" },
            ["relic.ThornShield"] = new[] { "가시 방패", "Thorn Shield" },
            ["relic.ThornShield.desc"] = new[] { "나를 때린 적은 {0} 피해를 받는다", "Attackers who hit me take {0}" },
            ["relic.VeteranHelm"] = new[] { "노병의 투구", "Veteran's Helm" },
            ["relic.VeteranHelm.desc"] = new[] { "전투 시작 시 내게 철벽 1회", "Start each battle with 1 Bulwark charge" },
            ["relic.WarBanner"] = new[] { "군기", "War Banner" },
            ["relic.WarBanner.desc"] = new[] { "첫 턴 아군 공격 +{0}", "Allies deal +{0} on turn one" },
            ["relic.GoldMagnet"] = new[] { "금화 자석", "Gold Magnet" },
            ["relic.GoldMagnet.desc"] = new[] { "전투 보상 +{0}G", "Battle rewards +{0}G" },
            ["relic.WaterSkin"] = new[] { "물주머니", "Water Skin" },
            ["relic.WaterSkin.desc"] = new[] { "휴식 회복량 +{0}%", "Rest heals +{0}% more" },
            ["relic.VictoryMeal"] = new[] { "승전 축배", "Victory Meal" },
            ["relic.VictoryMeal.desc"] = new[] { "전투 승리 시 내 HP {0} 회복", "Heal me {0} after each victory" },
            ["relic.IronHeart"] = new[] { "강철 심장", "Iron Heart" },
            ["relic.IronHeart.desc"] = new[] { "내 최대 HP +{0}", "My max HP +{0}" },
            ["relic.MerchantSeal"] = new[] { "상인 인장", "Merchant's Seal" },
            ["relic.MerchantSeal.desc"] = new[] { "상점 가격 -{0}%", "Shop prices -{0}%" },
            ["relic.OldStandard"] = new[] { "낡은 깃발", "Old Standard" },
            ["relic.OldStandard.desc"] = new[] { "도발 지속 +{0}턴", "Taunt lasts +{0} turn" },
            ["relic.GuardCharm"] = new[] { "수호 부적", "Guardian Charm" },
            ["relic.GuardCharm.desc"] = new[] { "수호 낙인의 내 분담 -{0}", "Guardian Mark's shared damage -{0}" },

            // v0.7 — 휴식 선택·강화·이벤트·상점·온보딩
            ["rest.choose"] = new[] { "모닥불 앞에서 하나를 고른다", "Choose one at the campfire" },
            ["rest.heal"] = new[] { "휴식한다 — 전원 {0}% 회복", "Rest — everyone heals {0}%" },
            ["rest.upgrade"] = new[] { "카드를 강화한다 (+)", "Upgrade a card (+)" },
            ["up.h1"] = new[] { "카드 강화", "Upgrade" },
            ["up.desc"] = new[] { "강화할 카드를 고르면 영구히 + 가 된다", "Pick a card to upgrade permanently" },
            ["up.done"] = new[] { "강화 완료", "Upgraded" },
            ["altar.h1"] = new[] { "수상한 제단", "Strange Altar" },
            ["altar.desc"] = new[] { "피를 원하는 제단이다. HP {0}을 바치면\n무언가 오래된 것이 눈을 뜬다.", "The altar craves blood. Offer {0} HP,\nand something ancient may awaken." },
            ["altar.offer"] = new[] { "피를 바친다 (내 HP -{0} → 유물)", "Offer blood (my HP -{0} → relic)" },
            ["altar.ignore"] = new[] { "지나친다", "Walk away" },
            ["scholar.h1"] = new[] { "떠돌이 학자", "Wandering Scholar" },
            ["scholar.desc"] = new[] { "\"자네 전술엔 군더더기가 있군.\n 한 수 지워주지 — 공짜로.\"", "\"Your tactics carry dead weight.\nLet me erase one — free of charge.\"" },
            ["scholar.remove"] = new[] { "카드 1장 제거 (무료)", "Remove a card (free)" },
            ["scholar.pick"] = new[] { "지울 카드를 골라라", "Pick a card to erase" },
            ["treasure.relic"] = new[] { "카드 대신 유물 상자를 연다", "Open the relic box instead" },
            ["shop.relic"] = new[] { "유물: {0}  ({1}G)\n{2}", "Relic: {0}  ({1}G)\n{2}" },
            ["title.continue"] = new[] { "이어하기", "Continue Run" },
            ["title.help"] = new[] { "게임 방법", "How to Play" },
            ["party.desc2"] = new[] { "{1}개 클래스 중 무작위 {0}명과 출발한다 — 매 원정 구성이 달라진다", "You set out with {0} random companions of {1} classes — every run differs" },
            ["party.noHealer"] = new[] { "⚠ 이번 원정엔 힐러가 없다 — 버티기·숨 고르기·응급 처치가 생명줄이다", "⚠ No healer this run — Brace, Respite and First Aid are your lifeline" },
            // ================= v1.0 대확장 =================
            // --- 신규 클래스 8 ---
            ["class.lancer"] = new[] { "창병", "Lancer" },
            ["class.venom"] = new[] { "독술사", "Venomancer" },
            ["class.druid"] = new[] { "드루이드", "Druid" },
            ["class.titan"] = new[] { "거인", "Titan" },
            ["class.arbalest"] = new[] { "노병 사수", "Arbalest" },
            ["class.monk"] = new[] { "수도승", "Monk" },
            ["class.seer"] = new[] { "점술사", "Seer" },
            ["class.squire"] = new[] { "종사", "Squire" },
            ["trait.LongReach"] = new[] { "장창: 후열에서도 공격 감소 없음 + 전열 아군 보호", "Long Reach: no back-row penalty, guards a front ally" },
            ["trait.Poison"] = new[] { "독: 공격에 독 중첩 — 매 턴 중첩만큼 피해", "Poison: stacks damage each turn" },
            ["trait.GroveHeal"] = new[] { "숲의 축복: 매 턴 동료 전원 회복", "Grove: heals every companion each turn" },
            ["trait.Retaliate"] = new[] { "보복: 맞을 때마다 공격력 누적", "Retaliate: attack grows each time hit" },
            ["trait.Volley"] = new[] { "연사: 두 적을 각각 절반 피해로 동시 사격", "Volley: hits two foes for half each" },
            ["trait.Focus"] = new[] { "집중: 카드를 쓰지 않은 턴엔 공격 2배", "Focus: double attack on turns you play no card" },
            ["trait.Foresight"] = new[] { "예지: 매 턴 카드 1장 더 뽑는다", "Foresight: draw one extra card each turn" },
            ["trait.Bulwark"] = new[] { "수호: 탱커가 받는 피해 -1", "Bulwark: tank takes -1 damage" },
            // --- 신규 적 15 + 보스 3 ---
            ["unit.ooze"] = new[] { "분열 슬라임", "Splitting Ooze" },
            ["unit.oozelet"] = new[] { "분열체", "Oozelet" },
            ["unit.silencer"] = new[] { "주술 방해자", "Silencer" },
            ["unit.gazer"] = new[] { "응시자", "Gazer" },
            ["unit.piercer"] = new[] { "관통 오거", "Piercer" },
            ["unit.effigy"] = new[] { "저주 인형", "Cursed Effigy" },
            ["unit.leech"] = new[] { "흡혈 정령", "Leech Spirit" },
            ["unit.rat"] = new[] { "역병 쥐", "Plague Rat" },
            ["unit.zealot"] = new[] { "광신도", "Zealot" },
            ["unit.bramble"] = new[] { "가시 덩굴", "Bramble" },
            ["unit.breaker"] = new[] { "방패 파괴자", "Shield Breaker" },
            ["unit.mirror"] = new[] { "거울 정령", "Mirror Spirit" },
            ["unit.burrower"] = new[] { "굴착 벌레", "Burrower" },
            ["unit.rot"] = new[] { "부패 술사", "Rotmancer" },
            ["unit.twin"] = new[] { "쌍둥이 검사", "Twin Blade" },
            ["unit.sentinel"] = new[] { "동면 골렘", "Dormant Sentinel" },
            ["unit.brood"] = new[] { "거미 여왕", "Broodmother" },
            ["unit.broodling"] = new[] { "새끼 거미", "Broodling" },
            ["unit.colossus"] = new[] { "강철 파괴자", "Steel Colossus" },
            ["unit.wyrm"] = new[] { "심연의 용", "Abyss Wyrm" },
            ["enc.brood"] = new[] { "거미 여왕", "Broodmother" },
            ["enc.colossus"] = new[] { "강철 파괴자", "Steel Colossus" },
            ["enc.wyrm"] = new[] { "심연의 용", "Abyss Wyrm" },
            // --- 신규 카드 24 ---
            ["card.Reposition"] = new[] { "교대", "Reposition" },
            ["card.Reposition.desc"] = new[] { "아군 1명 전열↔후열 전환 + 이번 턴 그 아군 피해 -{0}", "Swap an ally's row + they take -{0} this turn" },
            ["card.Reposition.s"] = new[] { "열 전환", "Swap row" },
            ["card.Vanguard"] = new[] { "선봉", "Vanguard" },
            ["card.Vanguard.desc"] = new[] { "이번 턴 전열 아군 전원 공격 +{0}", "Front-row allies +{0} attack this turn" },
            ["card.Vanguard.s"] = new[] { "전열 화력", "Front power" },
            ["card.Rearguard"] = new[] { "후위 정렬", "Rearguard" },
            ["card.Rearguard.desc"] = new[] { "이번 턴 후열 아군 전원 받는 피해 -{0}", "Back-row allies take -{0} this turn" },
            ["card.Rearguard.s"] = new[] { "후열 보호", "Back guard" },
            ["card.Barricade"] = new[] { "방벽", "Barricade" },
            ["card.Barricade.desc"] = new[] { "{1}턴간 아군 전원 받는 피해 -{0}", "All allies take -{0} for {1} turns" },
            ["card.Barricade.s"] = new[] { "지속 감산", "Lasting guard" },
            ["card.Vow"] = new[] { "불굴의 서약", "Vow" },
            ["card.Vow.desc"] = new[] { "{1}턴간 매 턴 내 HP {0} 회복", "Heal {0} each turn for {1} turns" },
            ["card.Vow.s"] = new[] { "지속 회복", "Regen" },
            ["card.Aegis"] = new[] { "수호 방벽", "Aegis" },
            ["card.Aegis.desc"] = new[] { "{1}턴간 내가 받는 한 방 상한 {0}", "Cap each hit on me at {0} for {1} turns" },
            ["card.Aegis.s"] = new[] { "지속 상한", "Lasting cap" },
            ["card.Awaken"] = new[] { "각성", "Awaken" },
            ["card.Awaken.desc"] = new[] { "내 HP {0} 지불 → 이번 턴 카드 1장 더 사용", "Pay {0} HP → play one more card this turn" },
            ["card.Awaken.s"] = new[] { "카드 1장 더", "Extra play" },
            ["card.Scout"] = new[] { "정찰", "Scout" },
            ["card.Scout.desc"] = new[] { "카드 {0}장 즉시 드로우", "Draw {0} cards now" },
            ["card.Scout.s"] = new[] { "드로우", "Draw" },
            ["card.Discipline"] = new[] { "군율", "Discipline" },
            ["card.Discipline.desc"] = new[] { "버린 더미를 즉시 뽑을 더미로 섞는다", "Shuffle discard back into draw now" },
            ["card.Discipline.descPlus"] = new[] { "리셔플 + 카드 1장 드로우", "Reshuffle + draw 1" },
            ["card.Discipline.s"] = new[] { "리셔플", "Reshuffle" },
            ["card.Feint"] = new[] { "교란", "Feint" },
            ["card.Feint.desc"] = new[] { "적 1명 이번 턴 허공 공격 (보스도 가능) — 다음 턴 그 적 공격 +{0}", "One foe wastes its turn (bosses too) — it gains +{0} next turn" },
            ["card.Feint.descPlus"] = new[] { "적 1명 이번 턴 허공 공격 — 반동 없음", "One foe wastes its turn — no backlash" },
            ["card.Feint.s"] = new[] { "허공 공격", "Wasted" },
            ["card.Purge"] = new[] { "정화의 빛", "Purge" },
            ["card.Purge.desc"] = new[] { "아군 전원 위축·독·석화 해제", "Clear Shaken/Poison/Petrify from all allies" },
            ["card.Purge.descPlus"] = new[] { "전원 상태 해제 + 각 {0} 회복", "Clear all + heal each {0}" },
            ["card.Purge.s"] = new[] { "전원 정화", "Purge all" },
            ["card.Antidote"] = new[] { "해독", "Antidote" },
            ["card.Antidote.desc"] = new[] { "아군 1명 독 제거 + 제거한 중첩만큼 회복", "Cure an ally's poison + heal that much" },
            ["card.Antidote.descPlus"] = new[] { "독 제거 + 중첩 2배 회복", "Cure poison + heal double" },
            ["card.Antidote.s"] = new[] { "독 제거", "Cure" },
            ["card.Silence"] = new[] { "침묵", "Silence" },
            ["card.Silence.desc"] = new[] { "적 1명의 특수 능력 이번 턴 무효", "Nullify one foe's special this turn" },
            ["card.Silence.descPlus"] = new[] { "특수 능력 무효 + 행동 취소", "Nullify special + cancel its action" },
            ["card.Silence.s"] = new[] { "능력 무효", "Nullify" },
            ["card.Warsong"] = new[] { "속공", "War Song" },
            ["card.Warsong.desc"] = new[] { "아군 1명 이번 턴 공격 {0}배", "One ally attacks {0}x this turn" },
            ["card.Warsong.s"] = new[] { "공격 배수", "Multiply" },
            ["card.Bless"] = new[] { "축복", "Bless" },
            ["card.Bless.desc"] = new[] { "아군 1명 이번 턴 받는 피해 전부 무효", "One ally takes no damage this turn" },
            ["card.Bless.descPlus"] = new[] { "피해 전부 무효 + 위축 해제", "No damage + clear Shaken" },
            ["card.Bless.s"] = new[] { "완전 방어", "Immune" },
            ["card.Inspire"] = new[] { "격려", "Inspire" },
            ["card.Inspire.desc"] = new[] { "이번 턴 아군 전원 공격 +{0}", "All allies +{0} attack this turn" },
            ["card.Inspire.s"] = new[] { "전원 화력", "All power" },
            ["card.Sacrifice"] = new[] { "대속", "Sacrifice" },
            ["card.Sacrifice.desc"] = new[] { "아군 1명 최대까지 회복 — 그만큼 내 HP 지불", "Fully heal an ally — pay that much of my HP" },
            ["card.Sacrifice.descPlus"] = new[] { "아군 1명 완전 회복 — 절반만 지불", "Fully heal an ally — pay only half" },
            ["card.Sacrifice.s"] = new[] { "완전 회복", "Full heal" },
            ["card.Counter"] = new[] { "반격 태세", "Riposte" },
            ["card.Counter.desc"] = new[] { "이번 턴 맞은 횟수 × {0} 피해를 마지막 공격자에게", "Deal hits taken × {0} to the last attacker" },
            ["card.Counter.s"] = new[] { "반격", "Riposte" },
            ["card.Fortress"] = new[] { "요새화", "Fortress" },
            ["card.Fortress.desc"] = new[] { "이번 턴 내 피해 절반 + 동료 전원 -{0}", "Halve my damage + allies -{0} this turn" },
            ["card.Fortress.s"] = new[] { "절반+전원", "Half+all" },
            ["card.Undying"] = new[] { "불굴", "Undying" },
            ["card.Undying.desc"] = new[] { "이번 전투 1회, 치명 피해를 HP {0}로 버틴다", "Once this battle, survive a fatal hit at {0} HP" },
            ["card.Undying.s"] = new[] { "치명 보험", "Survive" },
            ["card.Grudge"] = new[] { "원한", "Grudge" },
            ["card.Grudge.desc"] = new[] { "이번 턴 받은 피해의 절반만큼 다음 턴 아군 전원 공격 증가", "Next turn allies gain attack = half damage taken" },
            ["card.Grudge.descPlus"] = new[] { "받은 피해 전부만큼 다음 턴 아군 전원 공격 증가", "Next turn allies gain attack = all damage taken" },
            ["card.Grudge.s"] = new[] { "피해→화력", "Pain→power" },
            ["card.Barter"] = new[] { "흥정", "Barter" },
            ["card.Barter.desc"] = new[] { "즉시 골드 {0} 획득", "Gain {0} gold now" },
            ["card.Barter.s"] = new[] { "골드", "Gold" },
            ["card.Study"] = new[] { "관찰", "Study" },
            ["card.Study.desc"] = new[] { "적 1명을 2턴간 관찰 — 그 적 피해 -{0}", "Study a foe for 2 turns — it deals -{0}" },
            ["card.Study.s"] = new[] { "약점 관찰", "Study" },
            ["card.LastStand"] = new[] { "최후의 저항", "Last Stand" },
            ["card.LastStand.desc"] = new[] { "내 HP 절반 이하일 때만 — 이번 턴 완전 무적", "Only below half HP — I am immune this turn" },
            ["card.LastStand.s"] = new[] { "무적", "Invulnerable" },
            // --- 신규 유물 20 ---
            ["relic.StoneHeart"] = new[] { "석심", "Stone Heart" },
            ["relic.StoneHeart.desc"] = new[] { "전투 시작 시 방벽 {0}턴", "Barricade for {0} turns at battle start" },
            ["relic.BattleDrum"] = new[] { "전투 북", "Battle Drum" },
            ["relic.BattleDrum.desc"] = new[] { "아군 전원 공격 +{0}", "All allies +{0} attack" },
            ["relic.SilverBell"] = new[] { "은방울", "Silver Bell" },
            ["relic.SilverBell.desc"] = new[] { "전투 시작 시 카드 {0}장 추가 드로우", "Draw {0} extra card at battle start" },
            ["relic.BloodPact"] = new[] { "피의 계약", "Blood Pact" },
            ["relic.BloodPact.desc"] = new[] { "최대 HP -{0}, 아군 전원 공격 +{1}", "Max HP -{0}, all allies +{1} attack" },
            ["relic.TowerShield"] = new[] { "타워 실드", "Tower Shield" },
            ["relic.TowerShield.desc"] = new[] { "내가 받는 한 방 상한 {0}", "Cap each hit on me at {0}" },
            ["relic.Lodestone"] = new[] { "자철석", "Lodestone" },
            ["relic.Lodestone.desc"] = new[] { "적의 오라·무리 보너스 무효", "Nullify enemy aura and pack bonuses" },
            ["relic.SerpentRing"] = new[] { "뱀 반지", "Serpent Ring" },
            ["relic.SerpentRing.desc"] = new[] { "아군 공격에 독 {0}중첩 부여", "Ally hits apply {0} poison" },
            ["relic.HolyWater"] = new[] { "성수", "Holy Water" },
            ["relic.HolyWater.desc"] = new[] { "전투 시작 시 아군 전원 위축·독 해제", "Clear Shaken/Poison at battle start" },
            ["relic.WardStone"] = new[] { "방호석", "Ward Stone" },
            ["relic.WardStone.desc"] = new[] { "광역 피해 -{0}", "Area damage -{0}" },
            ["relic.CoinPurse"] = new[] { "동전 지갑", "Coin Purse" },
            ["relic.CoinPurse.desc"] = new[] { "방을 지날 때마다 골드 +{0}", "+{0} gold each room" },
            ["relic.SharpStone"] = new[] { "숫돌", "Whetstone" },
            ["relic.SharpStone.desc"] = new[] { "전투 첫 턴 아군 전원 공격 2배", "First turn: all allies double attack" },
            ["relic.GraveMoss"] = new[] { "무덤 이끼", "Grave Moss" },
            ["relic.GraveMoss.desc"] = new[] { "적을 처치할 때마다 내 HP +{0}", "+{0} HP whenever an enemy dies" },
            ["relic.RunedChain"] = new[] { "룬 사슬", "Runed Chain" },
            ["relic.RunedChain.desc"] = new[] { "도발로 받는 피해 -{0}", "-{0} damage from taunted foes" },
            ["relic.MirrorPlate"] = new[] { "거울 판금", "Mirror Plate" },
            ["relic.MirrorPlate.desc"] = new[] { "직격 시 {0}% 반사", "Reflect {0}% of direct hits" },
            ["relic.FieldRation"] = new[] { "야전 식량", "Field Ration" },
            ["relic.FieldRation.desc"] = new[] { "방을 지날 때마다 동료 전원 +{0}", "Companions heal {0} each room" },
            ["relic.SoulLantern"] = new[] { "영혼 등불", "Soul Lantern" },
            ["relic.SoulLantern.desc"] = new[] { "카드 보상 선택지 +1", "+1 card reward choice" },
            ["relic.BoneWhistle"] = new[] { "뼈 피리", "Bone Whistle" },
            ["relic.BoneWhistle.desc"] = new[] { "전투 첫 턴 적 하나 무력화 (보스 제외)", "Stun one non-boss foe on turn 1" },
            ["relic.ThickHide"] = new[] { "두꺼운 가죽", "Thick Hide" },
            ["relic.ThickHide.desc"] = new[] { "동료가 받는 피해 -{0}", "Companions take -{0} damage" },
            ["relic.LuckyDice"] = new[] { "행운의 주사위", "Lucky Dice" },
            ["relic.LuckyDice.desc"] = new[] { "보물 골드 +{0}%", "Treasure gold +{0}%" },
            ["relic.Titanite"] = new[] { "티탄석", "Titanite" },
            ["relic.Titanite.desc"] = new[] { "강화(+) 카드 수치 +{0}", "Upgraded cards gain +{0}" },
            // --- 3막·신규 이벤트·상태 로그 ---
            ["descend.h1b"] = new[] { "나락으로", "Into the Abyss" },
            ["descend.desc2"] = new[] { "심층 아래에 더 깊은 구멍이 있다.\n용의 숨결이 올라온다 — 진짜 끝은 저 아래다.", "Below the deep lies deeper still.\nDragon breath rises — the true end is down there." },
            ["descend.go2"] = new[] { "나락으로 내려간다 (3막)", "Descend into the Abyss (Act 3)" },
            ["ev3.h1"] = new[] { "무너진 도서관", "Ruined Library" },
            ["ev3.desc"] = new[] { "먼지 쌓인 전술서가 흩어져 있다.\n하나쯤은 아직 읽을 수 있겠다.", "Dusty tactical tomes lie scattered.\nOne might still be readable." },
            ["ev3.a"] = new[] { "전술서를 읽는다 — 카드 1장 무료 강화", "Read a tome — upgrade a card for free" },
            ["ev3.b"] = new[] { "책을 팔아치운다 (+{0}G)", "Sell the books (+{0}G)" },
            ["ev4.h1"] = new[] { "버려진 야영지", "Abandoned Camp" },
            ["ev4.desc"] = new[] { "식은 모닥불과 남겨진 짐.\n쉬어 갈 수도, 뒤져 갈 수도 있다.", "Cold embers and left-behind packs.\nRest here, or ransack it." },
            ["ev4.a"] = new[] { "쉬어 간다 — 전원 {0}% 회복", "Rest — all heal {0}%" },
            ["ev4.b"] = new[] { "짐을 뒤진다 (+{0}G)", "Ransack the packs (+{0}G)" },
            ["ev5.h1"] = new[] { "떠도는 유물상", "Wandering Relic Dealer" },
            ["ev5.desc"] = new[] { "후드 아래 눈이 반짝인다.\n\"값만 맞으면 뭐든 팔지.\"", "Eyes glint beneath the hood.\n\"For the right price, anything.\"" },
            ["ev5.a"] = new[] { "유물을 산다 ({0}G)", "Buy a relic ({0}G)" },
            ["ev5.b"] = new[] { "그냥 지나간다", "Walk away" },
            ["ev6.h1"] = new[] { "도박꾼", "The Gambler" },
            ["ev6.desc"] = new[] { "\"동전 던지기 한 판. 두 배로 주거나, 다 가져간다.\"", "\"One coin flip. Double it, or lose it all.\"" },
            ["ev6.a"] = new[] { "{0}G를 건다 — 두 배 또는 전액 상실", "Bet {0}G — double or nothing" },
            ["ev6.b"] = new[] { "도박은 안 한다", "Refuse the bet" },
            ["ev7.h1"] = new[] { "저주받은 우물", "Cursed Well" },
            ["ev7.desc"] = new[] { "우물 안에서 속삭임이 올라온다.\n피를 바치면 지혜를 준다고.", "Whispers rise from the well.\nBlood for knowledge, it says." },
            ["ev7.a"] = new[] { "피를 바친다 (나 -{0}) — 카드 2장 획득", "Offer blood (Me -{0}) — gain 2 cards" },
            ["ev7.b"] = new[] { "우물을 덮는다", "Cover the well" },
            ["ev8.h1"] = new[] { "버려진 대장간", "Abandoned Forge" },
            ["ev8.desc"] = new[] { "화덕에 아직 불씨가 남아 있다.\n장비를 손볼 수 있겠다.", "Embers still glow in the forge.\nYou could work your gear." },
            ["ev8.a"] = new[] { "카드를 벼린다 ({0}G) — 1장 강화", "Forge a card ({0}G) — upgrade 1" },
            ["ev8.b"] = new[] { "남은 약초를 챙긴다 — 회복", "Take leftover herbs — heal" },
            ["ev9.h1"] = new[] { "굶주린 동료", "Starving Companions" },
            ["ev9.desc"] = new[] { "동료들이 지쳐 주저앉았다.\n비상 식량을 풀지, 아껴 팔지.", "Your companions slump, exhausted.\nBreak out rations, or sell them." },
            ["ev9.a"] = new[] { "식량을 푼다 — 동료 전원 완전 회복", "Share rations — fully heal companions" },
            ["ev9.b"] = new[] { "식량을 팔아치운다 (+{0}G)", "Sell the rations (+{0}G)" },
            ["ev10.h1"] = new[] { "수상한 상자", "Suspicious Chest" },
            ["ev10.desc"] = new[] { "자물쇠가 너무 새것이다.\n미끼일 수도 있다.", "The lock looks far too new.\nIt could be bait." },
            ["ev10.a"] = new[] { "상자를 연다 — 유물 또는 함정", "Open it — relic or trap" },
            ["ev10.b"] = new[] { "건드리지 않는다", "Leave it alone" },
            ["ev11.h1"] = new[] { "순례자", "The Pilgrim" },
            ["ev11.desc"] = new[] { "성문 앞의 순례자가 축복을 팔고 있다.", "A pilgrim at the gate sells blessings." },
            ["ev11.a"] = new[] { "축복을 받는다 ({0}G) — 최대 HP +{1} 영구", "Take the blessing ({0}G) — +{1} max HP permanently" },
            ["ev11.b"] = new[] { "기도만 하고 지나간다", "Just pray and move on" },
            // --- 신규 전투 로그·팝업 ---
            ["log.petrified"] = new[] { "{0}는 석화되어 움직이지 못한다", "{0} is petrified and cannot act" },
            ["pop.petrified"] = new[] { "석화!", "Petrified!" },
            ["log.volley"] = new[] { "{0}의 연사 — 각 {1}", "{0} volleys — {1} each" },
            ["log.mirror"] = new[] { "{0}가 {1}의 공격을 반사했다", "{0} reflects {1}'s attack" },
            ["pop.mirror"] = new[] { "반사!", "Reflect!" },
            ["pop.poison"] = new[] { "독 {0}", "Poison {0}" },
            ["log.poisonTick"] = new[] { "독이 퍼진다", "The poison spreads" },
            ["pop.transfer"] = new[] { "전가 -{0}", "Transfer -{0}" },
            ["log.seal"] = new[] { "{0}가 카드 하나를 봉인했다", "{0} seals one of your cards" },
            ["log.petrify"] = new[] { "{0}의 응시 — {1} 석화", "{0} gazes — {1} petrified" },
            ["log.rot"] = new[] { "{0}가 이번 턴 회복을 막았다", "{0} blocks healing this turn" },
            ["log.dispel"] = new[] { "{0}가 내 방어를 부숴버렸다", "{0} shatters my defenses" },
            ["pop.dispel"] = new[] { "해제!", "Dispelled!" },
            ["log.hidden"] = new[] { "{0}는 몸을 숨겼다", "{0} is hidden" },
            ["log.split"] = new[] { "{0}의 잔해에서 {1}마리가 일어났다", "{1} spawn from {0}'s remains" },
            ["log.spawn"] = new[] { "{0}가 새끼 {1}마리를 낳았다", "{0} spawns {1} broodlings" },
            ["log.env"] = new[] { "{0}의 가시가 모두를 긁는다", "{0}'s thorns rake everyone" },
            ["log.counter"] = new[] { "반격! {0}에게 {1}", "Riposte! {1} to {0}" },
            ["log.undying"] = new[] { "쓰러지지 않는다!", "I will not fall!" },
            ["pop.undying"] = new[] { "불굴!", "Undying!" },
            ["log.extraPlay"] = new[] { "각성 — 카드를 한 장 더 쓸 수 있다", "Awakened — play one more card" },
            ["log.grove"] = new[] { "{0}의 숲 축복 — 동료 전원 +{1}", "{0}'s grove blessing — companions +{1}" },
            ["log.enrageBrood"] = new[] { "{0}가 광란한다!", "{0} goes berserk!" },
            ["log.enrageColossus"] = new[] { "{0}의 장갑이 갈라진다!", "{0}'s plating cracks!" },
            ["log.enrageWyrm"] = new[] { "{0}가 포효한다 — 하늘이 타오른다!", "{0} roars — the sky burns!" },
            ["pop.deathbuff"] = new[] { "유언!", "Last words!" },
            ["pop.pierce"] = new[] { "관통!", "Pierce!" },
            ["pop.reposition"] = new[] { "교대!", "Swap!" },
            ["pop.barricade"] = new[] { "방벽!", "Barricade!" },
            ["pop.vow"] = new[] { "서약!", "Vow!" },
            ["pop.awaken"] = new[] { "각성!", "Awaken!" },
            ["pop.feint"] = new[] { "교란!", "Feint!" },
            ["pop.purge"] = new[] { "정화!", "Purge!" },
            ["pop.antidote"] = new[] { "해독!", "Cured!" },
            ["pop.silence"] = new[] { "침묵!", "Silenced!" },
            ["pop.warsong"] = new[] { "속공!", "War song!" },
            ["pop.bless"] = new[] { "축복!", "Blessed!" },
            ["pop.study"] = new[] { "관찰!", "Studied!" },
            ["pop.laststand"] = new[] { "최후의 저항!", "Last stand!" },
            ["intent.seal"] = new[] { "카드 봉인", "Seals a card" },
            ["intent.petrify"] = new[] { "{0} 석화", "Petrifies {0}" },
            ["intent.dispel"] = new[] { "내 방어 해제", "Dispels my guards" },
            ["intent.rot"] = new[] { "회복 차단", "Blocks healing" },
            ["intent.hidden"] = new[] { "잠복 (피해 무효)", "Hidden (immune)" },
            ["intent.wake"] = new[] { "각성까지 {0}턴", "Wakes in {0}" },
            ["intent.env"] = new[] { "전원 {0} (회피 불가)", "All {0} (unavoidable)" },
            ["st.poison"] = new[] { "독 {0}", "Poison {0}" },
            ["st.pierce"] = new[] { "방패·엄호 관통", "Ignores shields & cover" },
            ["st.reflect"] = new[] { "피해 전가", "Transfers damage" },
            ["st.healblock"] = new[] { "회복 절반", "Halves healing" },
            ["st.split"] = new[] { "죽으면 분열", "Splits on death" },
            ["st.mirror"] = new[] { "공격 1회 반사", "Reflects one hit" },
            ["st.deathbuff"] = new[] { "죽으면 동료 강화", "Buffs allies on death" },
            ["st.sealed"] = new[] { "봉인", "Sealed" },
            ["item.plate"] = new[] { "강철 판금", "Steel Plating" },
            ["item.plate.desc"] = new[] { "최대 HP +{0} (영구)", "Max HP +{0} (permanent)" },
            ["codex.melee"] = new[] { "근접", "Melee" },
            ["codex.ranged"] = new[] { "원거리", "Ranged" },
            ["form.0"] = new[] { "기본 진형", "Standard" },
            ["form.1"] = new[] { "밸런스 진형", "Balanced" },
            ["form.2"] = new[] { "공격 진형", "Assault" },
            ["form.3"] = new[] { "보호 진형", "Guardian" },
            ["form.0.desc"] = new[] { "근접은 전열, 원거리는 후열 — 표준 배치", "Melee front, ranged back — the standard" },
            ["form.1.desc"] = new[] { "최강 근접 하나만 전열 — 창끝만 세우고 나머지는 안전", "One spearhead in front — everyone else stays safe" },
            ["form.2.desc"] = new[] { "전원 전열 — 전원 공격 +{0}, 대신 전원이 근접의 표적", "All front — everyone +{0} atk, but everyone is a melee target" },
            ["form.3.desc"] = new[] { "전원 후열 — 동료 받는 피해 -{1}, 대신 근접 적이 후열까지 온다", "All back — allies take -{1} damage, but melee foes reach the back" },
            ["party.front"] = new[] { "전열", "Front" },
            ["party.back"] = new[] { "후열", "Back" },
            ["party.rowHint"] = new[] { "배치: 근접은 전열 공격 +{0}·후열 -{1} — 적 근접은 전열부터, 도약·매복 적은 배치 무시", "Formation: melee +{0} atk in front, -{1} in back — melee foes hit front first; leapers/ambushers ignore rows" },

            // v0.7 — 게임 방법 4페이지
            ["help.t0"] = new[] { "1. 나는 공격하지 않는다", "1. I don't attack" },
            ["help.b0"] = new[] { "동료들이 알아서 싸운다. 나는 탱커 — 적의 공격 예고(빨간 선과 숫자)를 읽고, 카드로 팀을 지킨다.\n\n· 적 머리 위 예고 = 이번 턴 그 적이 할 일\n· 아군 아래 '예상 -N' = 지금 이대로 진행하면 받을 피해\n· 위축: 피해를 입은 아군은 다음 행동이 절반 — 막는 것이 곧 화력이다", "Your companions fight on their own. You are the tank — read enemy intents (red lines and numbers) and protect the team with cards.\n\n· The label above an enemy = what it will do this turn\n· 'Incoming -N' under an ally = damage if you do nothing\n· Shaken: a hurt ally acts at half power — protecting IS damage" },
            ["help.t1"] = new[] { "2. 카드는 예약제", "2. Cards are reservations" },
            ["help.b1"] = new[] { "매 턴 4장을 뽑아 1장만 쓴다.\n\n· 카드를 탭 → (대상 카드면) 빛나는 대상을 탭 → 진행\n· 진행을 누르기 전엔 언제든 취소 가능\n· 안 쓴 손패는 버려지고, 덱이 떨어지면 버림 더미를 섞어 다시 쓴다\n· 카드를 아끼는 턴도 유효한 전략이다", "Draw 4 each turn, play at most 1.\n\n· Tap a card → (if targeted) tap a glowing unit → Go\n· Cancel anytime before pressing Go\n· Unplayed cards are discarded; when the deck runs dry the discard pile is reshuffled\n· Saving your card is a valid play" },
            ["help.t2"] = new[] { "3. 파티는 매번 다르다", "3. Every party is different" },
            ["help.b2"] = new[] { "원정마다 12개 클래스에서 무작위 동료가 온다. 전원 고유 능력이 있다.\n\n· 힐러(클레릭)가 없으면 회복 카드가 생명줄\n· 광전사는 반피 이하일 때, 문지기는 풀피일 때 강하다 — 누굴 지킬지가 곧 빌드\n· 첫 원정만 고정 파티로 시작한다", "Each run brings random companions from 12 classes, all with unique abilities.\n\n· No cleric? Healing cards are your lifeline\n· The Berserker is strong below half HP, the Warden at full — who you protect is your build\n· Only your first run uses a fixed party" },
            ["help.t3"] = new[] { "4. 던전은 갈림길이다", "4. The dungeon branches" },
            ["help.b3"] = new[] { "연결된 방만 갈 수 있다. 깊이 내려갈수록 적이 강해진다.\n\n· 엘리트: 강하지만 유물(영구 패시브) 확정\n· 휴식: 회복 또는 카드 강화 택1\n· 상점·보물·함정을 경로에 넣을지가 전략\n· 방을 마칠 때마다 자동 저장된다 — 언제든 이어하기", "You can only move along connected rooms. Enemies grow stronger the deeper you go.\n\n· Elite: tough, but a guaranteed relic (permanent passive)\n· Rest: heal OR upgrade a card\n· Routing through shops, treasure and traps is the strategy\n· Progress auto-saves after every room — continue anytime" },

            // ---- v0.4: 전투 UI/로그 ----
            ["bt.deck"] = new[] { "핸드 {0} · 덱 {1}", "Hand {0} · Deck {1}" },
            ["hint.cards"] = new[] { "카드 1장 사용(선택) 후 진행 — 진행 전엔 언제든 취소 가능", "Play up to 1 card, then Go — cancel any time before Go" },
            ["log.planCard"] = new[] { "{0} 예약 (진행 시 확정)", "{0} planned (commits on Go)" },
            ["log.planCardTarget"] = new[] { "{0} 예약 → {1} (진행 시 확정)", "{0} planned → {1} (commits on Go)" },
            ["log.pickEnemy"] = new[] { "대상 적을 선택", "Choose an enemy" },
            ["log.pickAlly"] = new[] { "대상 아군을 선택", "Choose an ally" },
            ["log.shoveBossImmune"] = new[] { "보스는 밀쳐낼 수 없다", "The boss cannot be shoved" },
            ["log.allyHit"] = new[] { "{0}이(가) {1}에게 {2} 피해", "{0} hits {1} for {2}" },
            ["log.stunned"] = new[] { "{0}이(가) 밀쳐져 행동하지 못한다", "{0} is shoved and loses its action" },
            ["log.curseWasted"] = new[] { "{0}의 저주가 나에게는 통하지 않는다", "{0}'s curse has no hold on me" },
            ["log.curse"] = new[] { "{0}이(가) {1}에게 위축의 저주를 걸었다", "{0} curses {1} with Shaken" },
            ["log.blocked"] = new[] { "{0}의 방패가 공격을 통째로 막아냈다", "{0}'s bulwark blocks the hit entirely" },
            ["pop.shield"] = new[] { "철벽!", "Bulwark!" },
            ["pop.shove"] = new[] { "밀쳐냄!", "Shoved!" },
            ["pop.stunnedMark"] = new[] { "행동 불가", "No action" },
            ["pop.cursed"] = new[] { "저주!", "Cursed!" },
            ["pop.rally"] = new[] { "사기 회복!", "Rallied!" },
            ["pop.phalanx"] = new[] { "결사 방어!", "Last Stand!" },
            ["pop.oath"] = new[] { "맹세!", "Oath!" },
            ["pop.blocked"] = new[] { "무효!", "Blocked!" },
            ["st.stunned"] = new[] { "밀쳐짐", "Shoved" },
            ["st.shielded"] = new[] { "철벽 {0}", "Bulwark {0}" },
            ["st.cardPlanned"] = new[] { "{0} 예약", "{0} planned" },
            ["intent.stunned"] = new[] { "밀쳐짐 — 행동 불가", "Shoved — no action" },
            ["intent.curse"] = new[] { "저주 ▶ {0}", "Curse ▶ {0}" },
            ["intent.curseWasted"] = new[] { "저주 (도발됨 — 불발)", "Curse (taunted — fizzles)" },

            // ---- v0.4: 파티/보상/제거 화면 ----
            ["party.h1"] = new[] { "오늘의 원정대", "Today's Expedition" },
            ["party.desc"] = new[] { "매 런마다 동료가 달라진다 — 이 파티로 끝까지 간다.", "Companions change every run — this party goes all the way." },
            ["party.go"] = new[] { "출발 ▶", "Set out ▶" },
            ["party.attack"] = new[] { "HP {0} · 공격 {1}", "HP {0} · Attack {1}" },
            ["party.heal"] = new[] { "HP {0} · 치유 {1} (백라이너 전담)", "HP {0} · Heal {1} (backline only)" },
            ["party.tank"] = new[] { "HP {0} · 공격 없음 — 팀을 지킨다", "HP {0} · No attacks — I protect" },
            ["map.deck"] = new[] { "덱 {0}장", "Deck: {0} cards" },
            ["reward.h1"] = new[] { "전리품 — 카드 1장", "Spoils — Pick a Card" },
            ["reward.desc"] = new[] { "덱에 넣을 카드를 고르거나, 덱을 가볍게 유지하라.", "Add a card to your deck, or keep it lean." },
            ["reward.skip"] = new[] { "넘어간다", "Skip" },
            ["shop.remove"] = new[] { "카드 제거  ({0}G)", "Remove a card  ({0}G)" },
            ["remove.h1"] = new[] { "카드 제거", "Remove a Card" },
            ["remove.desc"] = new[] { "제거할 카드를 선택 ({0}G) — 덱이 가벼울수록 원하는 카드가 자주 온다.", "Pick a card to remove ({0}G) — a lean deck draws what you need." },
            ["remove.back"] = new[] { "돌아간다", "Back" },
            ["rest.desc2"] = new[] { "잠시나마 등을 벽에 기댄다.\n전원 회복 (나 +{0})", "For a moment, we rest our backs against the wall.\nEveryone recovers (Me +{0})" },
            ["end.retrySame"] = new[] { "같은 원정 재도전 — 구성·맵·조우 그대로", "Retry this run — same party, map & foes" },
        };
    }
}
